<a href="https://colab.research.google.com/github/vi0rend/AVD-Alvionej-Resna/blob/main/Praktikum_AVD_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import pandas as pd

In [4]:
file_path = "/topuniversities.csv"

df = pd.read_csv(file_path)
df

,Rank,Ordinal Rank,University Name,Overall Score,City,Country,Citations per Paper,Papers per Faculty,Academic Reputation,Faculty Student Ratio,Staff with PhD,International Research Center,International Students,Outbound Exchange,Inbound Exchange,International Faculty,Employer Reputation
0,1,1,Peking University,100.0,Beijing,China,96.4,79.8,100.0,98.6,90.7,98.0,69.1,100.0,88.5,83.2,100.0
1,2,2,The University of Hong Kong,99.7,Pokfulam,Hong Kong,99.5,55.0,100.0,93.3,97.4,98.4,100.0,100.0,99.8,100.0,96.8
2,3,3,National University of Singapore (NUS),98.9,Singapore,Singapore,99.9,57.4,100.0,85.8,82.5,99.9,99.2,97.6,93.4,100.0,99.9
3,4,4,Nanyang Technological University,98.3,Singapore,Singapore,100.0,53.8,100.0,93.0,67.0,99.7,98.8,97.9,90.5,100.0,98.8
4,5,5,Fudan University,97.2,Shanghai,China,92.1,63.1,99.8,92.5,73.4,92.1,81.0,94.9,99.5,98.9,99.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,296,National Chinyi University of Technology,29.5,Taichung City,Taiwan,25.8,15.9,31.9,12.9,52.1,11.5,29.8,3.4,17.2,5.1,46.7
296,297,296,Sungshin Women's University,29.5,Seoul,South Korea,9.1,2.1,21.4,93.0,18.6,2.5,22.5,85.5,44.6,7.7,33.9
297,298,298,Northwest University (China),29.2,Xi'an,China,64.5,27.4,16.1,69.5,17.5,49.7,13.3,47.9,6.1,10.6,5.3
298,299,299,Ocean University of China,29.1,Qingdao,China,48.1,60.5,20.8,13.9,33.0,76.4,6.5,27.3,2.8,8.5,12.4
299,300,300,Huazhong Agricultural University,29.0,Wuhan,China,91.5,52.2,16.7,12.1,61.0,45.6,6.6,11.5,1.5,11.7,9.3

In [5]:
output_path ="/content/topuniversities.csv"
df.to_csv(output_path, index=False)

print("\nData berhasil disimpan sebagai file Excel:", output_path)

Data berhasil disimpan sebagai file Excel: /content/topuniversities.csv

# **BUSINESS UNDERSTANDING**

**Business Objective**

Tujuan utama dari proyek ini adalah untuk memahami faktor-faktor yang berkontribusi terhadap peringkat universitas di Asia berdasarkan QS Rankings 2024. Dengan menganalisis berbagai metrik seperti reputasi akademik, rasio fakultas terhadap mahasiswa, penelitian internasional, dan jumlah mahasiswa internasional, proyek ini bertujuan untuk mengidentifikasi pola yang memungkinkan universitas meningkatkan daya saing mereka. Selain itu, proyek ini juga bertujuan untuk memberikan wawasan bagi calon mahasiswa dan pemangku kepentingan dalam memilih institusi pendidikan terbaik.

**Assess Situation**

Industri pendidikan tinggi di Asia semakin kompetitif dengan banyak universitas yang berupaya meningkatkan kualitas akademik dan penelitian mereka. Perubahan dalam kebijakan pendidikan, tingkat internasionalisasi, serta reputasi akademik dan kerja turut memengaruhi peringkat universitas. Oleh karena itu, analisis mendalam terhadap data peringkat universitas menjadi penting untuk mengidentifikasi tren dan faktor yang memengaruhi daya saing institusi pendidikan.

**Data Mining Goals**

Menganalisis faktor-faktor utama yang memengaruhi peringkat universitas di Asia dengan mengidentifikasi hubungan antara berbagai metrik seperti reputasi akademik, jumlah sitasi per publikasi, jumlah mahasiswa internasional, serta tingkat pertukaran mahasiswa. Analisis ini juga bertujuan untuk memberikan wawasan tentang bagaimana universitas dapat meningkatkan kualitas akademik dan reputasi mereka dalam skala global.

**Project Plan**

Proyek ini dimulai dengan mengumpulkan dan membersihkan data dari QS Asian Rankings 2024. Data yang dikumpulkan mencakup indikator seperti reputasi akademik, jumlah sitasi per publikasi, rasio fakultas terhadap mahasiswa, dan jumlah mahasiswa internasional. Pembersihan data dilakukan untuk memastikan akurasi dan menghilangkan anomali.

Setelah itu, dilakukan analisis statistik untuk menemukan pola dan hubungan antara faktor-faktor yang memengaruhi peringkat universitas. Hasilnya akan disajikan dalam bentuk laporan dan visualisasi agar mudah dipahami oleh pemangku kepentingan. Proyek ini diakhiri dengan rekomendasi bagi universitas yang ingin meningkatkan daya saing mereka di tingkat internasional.

# DATA UNDERSTANDING

menampilkan ringkasan dataset

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Rank                           300 non-null    int64
 1   Ordinal Rank                   300 non-null    int64
 2   University Name                300 non-null    object
 3   Overall Score                  300 non-null    float64
 4   City                           300 non-null    object
 5   Country                        300 non-null    object
 6   Citations per Paper            300 non-null    float64
 7   Papers per Faculty             300 non-null    float64
 8   Academic Reputation            300 non-null    float64
 9   Faculty Student Ratio          300 non-null    float64
 10  Staff with PhD                 294 non-null    float64
 11  International Research Center  300 non-null    float64
 12  International Students         296 non-null    float64
 13  Outbound Exchange              300 non-null    float64
 14  Inbound Exchange               300 non-null    float64
 15  International Faculty          283 non-null    float64
 16  Employer Reputation            300 non-null    float64
dtypes: float64(12), int64(2), object(3)
memory usage: 40.0+ KB

Menampilkan jumlah baris dan kolom

In [7]:
df.shape

(300, 17)

Menghitung Korelasi Antar Kolom Numerik

In [8]:
df.corr(numeric_only=True)

,Rank,Ordinal Rank,Overall Score,Citations per Paper,Papers per Faculty,Academic Reputation,Faculty Student Ratio,Staff with PhD,International Research Center,International Students,Outbound Exchange,Inbound Exchange,International Faculty,Employer Reputation
Rank,1.000000,0.999968,-0.954643,-0.219652,-0.293990,-0.862827,-0.403355,-0.446959,-0.468019,-0.462322,-0.370927,-0.433121,-0.404889,-0.761246
Ordinal Rank,0.999968,1.000000,-0.954562,-0.219700,-0.293435,-0.862998,-0.403051,-0.446609,-0.468167,-0.461754,-0.370235,-0.432346,-0.404527,-0.761367
Overall Score,-0.954643,-0.954562,1.000000,0.268052,0.312004,0.896955,0.454798,0.455516,0.488723,0.513554,0.409723,0.469792,0.427801,0.763001
Citations per Paper,-0.219652,-0.219700,0.268052,1.000000,0.486041,-0.064392,0.004107,0.276578,0.452921,0.084009,0.175227,0.077214,0.043004,-0.143369
Papers per Faculty,-0.293990,-0.293435,0.312004,0.486041,1.000000,0.117506,-0.163080,0.559372,0.536401,-0.121409,-0.045673,-0.119361,-0.119792,-0.029458
Academic Reputation,-0.862827,-0.862998,0.896955,-0.064392,0.117506,1.000000,0.358035,0.297581,0.333821,0.391102,0.242586,0.332274,0.361890,0.793638
Faculty Student Ratio,-0.403355,-0.403051,0.454798,0.004107,-0.163080,0.358035,1.000000,0.110463,-0.097136,0.476343,0.435891,0.462519,0.359099,0.216891
Staff with PhD,-0.446959,-0.446609,0.455516,0.276578,0.559372,0.297581,0.110463,1.000000,0.320523,0.219162,0.138828,0.164336,0.059475,0.112035
International Research Center,-0.468019,-0.468167,0.488723,0.452921,0.536401,0.333821,-0.097136,0.320523,1.000000,-0.001793,-0.089033,-0.058656,-0.098278,0.129727
International Students,-0.462322,-0.461754,0.513554,0.084009,-0.121409,0.391102,0.476343,0.219162,-0.001793,1.000000,0.606147,0.647472,0.629185,0.330461
Outbound Exchange,-0.370927,-0.370235,0.409723,0.175227,-0.045673,0.242586,0.435891,0.138828,-0.089033,0.606147,1.000000,0.772452,0.576159,0.205801
Inbound Exchange,-0.433121,-0.432346,0.469792,0.077214,-0.119361,0.332274,0.462519,0.164336,-0.058656,0.647472,0.772452,1.000000,0.581555,0.301433
International Faculty,-0.404889,-0.404527,0.427801,0.043004,-0.119792,0.361890,0.359099,0.059475,-0.098278,0.629185,0.576159,0.581555,1.000000,0.316139
Employer Reputation,-0.761246,-0.761367,0.763001,-0.143369,-0.029458,0.793638,0.216891,0.112035,0.129727,0.330461,0.205801,0.301433,0.316139,1.000000

Menampilkan Statistik Deskriptif

In [9]:
df.describe()

,Rank,Ordinal Rank,Overall Score,Citations per Paper,Papers per Faculty,Academic Reputation,Faculty Student Ratio,Staff with PhD,International Research Center,International Students,Outbound Exchange,Inbound Exchange,International Faculty,Employer Reputation
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,294.000000,300.000000,296.000000,300.000000,300.000000,283.000000,300.000000
mean,150.500000,150.133333,52.057667,44.869667,41.288667,51.648000,50.976333,53.959524,60.108333,35.779054,38.573667,35.303667,38.437456,54.646000
std,86.746758,86.556739,19.123336,34.088756,29.994062,26.305925,31.338651,35.002787,31.179020,31.477270,34.467015,36.086228,30.571068,29.915534
min,1.000000,1.000000,29.000000,1.000000,1.200000,8.800000,2.600000,1.000000,1.100000,1.300000,1.000000,1.000000,1.000000,4.100000
25%,75.750000,75.750000,35.850000,11.075000,14.500000,30.100000,21.750000,15.850000,33.475000,9.175000,8.300000,3.300000,12.800000,28.150000
50%,150.500000,150.500000,46.250000,39.050000,36.750000,45.150000,47.850000,62.300000,67.100000,23.950000,28.100000,20.100000,29.500000,53.050000
75%,225.250000,225.250000,62.725000,76.150000,61.775000,67.550000,80.300000,86.800000,88.675000,58.100000,62.925000,67.800000,56.850000,81.850000
max,300.000000,300.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000


# Data Preparation


Missing Values

In [10]:
(df.isna().sum() / len(df)) * 100

Rank                             0.000000
Ordinal Rank                     0.000000
University Name                  0.000000
Overall Score                    0.000000
City                             0.000000
Country                          0.000000
Citations per Paper              0.000000
Papers per Faculty               0.000000
Academic Reputation              0.000000
Faculty Student Ratio            0.000000
Staff with PhD                   2.000000
International Research Center    0.000000
International Students           1.333333
Outbound Exchange                0.000000
Inbound Exchange                 0.000000
International Faculty            5.666667
Employer Reputation              0.000000
dtype: float64

melakukan